Description: Deploy an endpoint at Sagemaker
Parameters:
  Stage:
    Type: String
    Description: stage
  ImageRepoUri:
    Type: String
    Description: Uri of the docker (ECR) model image
  ModelName:
    Type: String
    Description: Name of the model
  ModelsPrefix:
    Type: String
    Description: S3 bucket where models are stored
  MLOpsRoleArn:
    Type: String
    Description: The role for executing the deployment

Resources:
  ModelsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ModelsPrefix}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
  Model:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: !Sub ${ModelName}-${Stage}
      PrimaryContainer:
        Image: !Ref ImageRepoUri
        ModelDataUrl: !Ref ModelBucket
        Mode: MultiModel
      ExecutionRoleArn: !Ref MLOpsRoleArn

  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: ml.t2.medium
          ModelName: !GetAtt Model.ModelName
          VariantName: AllTraffic
      EndpointConfigName: !Sub ${ModelName}-${Stage}

  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub ${ModelName}-${Stage}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
