version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo Pre-build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - echo Build and push container for Multi-Model-Endpoint
      - cd multi-model-endpoint/container
      - ./build_and_push.sh 
      - cd $CODEBUILD_SRC_DIR
      - echo Build and push container for training
      - cd training/container
      - ./build_and_push.sh 

  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - echo Run the workflow script
      - python multi-model-endpoint/run.py --model-name=$MODEL_NAME --stage=$STAGE --role=$ROLE_ARN --output-dir=assets --ecr-dir=multi-model-endpoint/container
      - echo TODO Train models
      - echo TODO Upload models to S3 bucket to be used by test Multi-Model-Endpoint

  post_build:
    commands:
      - echo TODO Create SageMaker Monitoring Baselines
      - echo TODO Create SageMaker Monitoring Schedule for Multi-Model-Endpoint
      - echo TODO Create Sagemaker final Multi-Model-Endpoint
      - cd $CODEBUILD_SRC_DIR

artifacts:
  files:
    - assets/*.json
    - assets/*.yml
  discard-paths: yes