version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Preparing building container"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo "Installing requirements"
      - pip install --upgrade pip
      - pip install -r $CODEBUILD_SRC_DIR/requirements.txt
      - pip install crhelper -t $CODEBUILD_SRC_DIR/custom_resource # Install custom resource helper into the CFN directory


  pre_build:
    commands:
      - echo Pre-build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - echo "Build and push container for Multi-Model-Endpoint"
      - cd multi-model-endpoint/container
      - ./build_and_push.sh 
      - cd $CODEBUILD_SRC_DIR
      - echo "Build and push container for training"
      - cd training/container
      - ./build_and_push.sh 
      - echo Get pipeline name
      - export PIPELINE_NAME=${CODEBUILD_INITIATOR#codepipeline/}
      - echo $PIPELINE_NAME

  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - echo Run the workflow script
      - python models/run.py --pipeline-name=$PIPELINE_NAME --model-name=$MODEL_NAME --stage=$STAGE --role=$ROLE_ARN --output-dir=assets --endpoint-dir=multi-model-endpoint --training-dir=training

  post_build:
    commands:
      - echo Package custom resources
      - aws cloudformation package --template-file custom_resource/sagemaker-custom-resource.yml --output-template-file assets/template-custom-resource.yml --s3-bucket $ARTIFACT_BUCKET
      - echo Done

artifacts:
  files:
    - assets/*.json
    - assets/*.yml
  discard-paths: yes