Description: Multi model deployment
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Required Parameters
        Parameters:
          - ModelName
      - Label:
          default: Optional GitHub Parameters
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubSecret
    ParameterLabels:
      ModelName:
        default: detektivkollektiv-ml-models
      GitHubRepo:
        default: ml-models
      GitHubBranch:
        default: develop
      GitHubUser:
        default: DetektivKollektiv
      GitHubSecret:
        default: GitHub/ML-models
Parameters:
  Stage:
    Default: dev
    Description: stage (corresponding to branch)
    Type: String
  ModelName:
    Default: detektivkollektiv-ml-models
    Type: String
    Description: Name of the model
    MinLength: 1
    MaxLength: 30
    AllowedPattern: '^[a-z0-9](-*[a-z0-9])*'
    ConstraintDescription: Must be lowercase or numbers with a length of 1-25 characters.
  GitHubUser:
    Default: DetektivKollektiv
    Description: Your GitHub username
    Type: String
  GitHubRepo:
    Default: ml-models
    Type: String
    Description: Name of the GitHub repository
  GitHubBranch:
    Default: develop
    Type: String
    Description: Name of the branch the code is located
  GitHubSecret:
    Default: GitHub/ML-models
    Type: String
    Description: Name of secret in the secretsmanager

Resources:
  ArtifactBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ModelName}-artifacts-${Stage}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
  BuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${ModelName}-build-${Stage}'
      Description: Build and push the multi-model image and train models
      ServiceRole: !GetAtt SageMakerRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:4.0'
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: ./buildspec.yml
      TimeoutInMinutes: 30
  CreateExperiment:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${ModelName}-create-experiment-${Stage}'
      Handler: index.lambda_handler
      MemorySize: 512
      Role: !GetAtt SageMakerRole.Arn
      Runtime: python3.8
      Timeout: 60
      Code:
        ZipFile: |
          import boto3
          import io
          import zipfile
          import json

          s3 = boto3.client('s3')
          sm = boto3.client('sagemaker')
          codepipeline = boto3.client('codepipeline')

          def lambda_handler(event, context):
              print('event', json.dumps(event))
              jobId = event["CodePipeline.job"]["id"]
              experiment = None
              trial = None

              try:
                  for inputArtifacts in event["CodePipeline.job"]["data"]["inputArtifacts"]:
                      if inputArtifacts['name'] == 'BuildOutput':
                          s3Location = inputArtifacts['location']['s3Location']
                          zip_bytes = s3.get_object(Bucket=s3Location['bucketName'], Key=s3Location['objectKey'])['Body'].read()
                          with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as z:
                            trials = json.loads(z.read('trials.json').decode('utf-8'))

                  if trials is None:
                    raise(Exception("Experiment and Trail config not found"))

                  for trial in trials:
                    try:
                        response = sm.create_experiment(ExperimentName=trial["ExperimentName"])
                        print('created exp', response)
                    except Exception as e:
                        print('error creating exp', e)
                    try:
                        response = sm.create_trial(ExperimentName=trial["ExperimentName"], TrialName=trial["TrialName"])
                        print('created trial', response)
                    except Exception as e:
                        print('error creating trial', e)

                  # and update codepipeline
                  codepipeline.put_job_success_result(jobId=jobId)
              except Exception as e:
                  print(e)
                  resp = codepipeline.put_job_failure_result(
                      jobId=jobId,
                      failureDetails={
                          'type': 'ConfigurationError',
                          'message': str(e),
                          'externalExecutionId': context.aws_request_id
                      }
                  )
              return 'Done'
      Description: Function that creates an experiment and trial
  DeployPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub '${ModelName}-${Stage}'
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location:
          Ref: ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Sub '{{resolve:secretsmanager:${GitHubSecret}:SecretString:token}}'
        - Name: Build
          Actions:
            - Name: BuildImage
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProject
                PrimarySource: SourceOutput
                EnvironmentVariables: !Sub >-
                  [{"name":"DATA_BUCKET","value":"sagemaker-${AWS::Region}-${AWS::AccountId}","type":"PLAINTEXT"}, {"name":"MODEL_NAME","value":"${ModelName}","type":"PLAINTEXT"},{"name":"STAGE","value":"${Stage}","type":"PLAINTEXT"},{"name":"ROLE_ARN","value":"${MLOpsRole.Arn}","type":"PLAINTEXT"}]
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployModelDev
              InputArtifacts:
                - Name: BuildOutput
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: !GetAtt MLOpsRole.Arn
                StackName: !Sub '${ModelName}-${Stage}'
                TemplateConfiguration: 'BuildOutput::deploy-endpoint.json'
                TemplatePath: 'BuildOutput::deploy-endpoint.yml'
              RunOrder: 1
  S3Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub '${ModelName}-s3-policy-${Stage}'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3Resources
            Effect: Allow
            Action:
              - 's3:CreateBucket'
              - 's3:GetBucket*'
              - 's3:GetObject*'
              - 's3:ListBucket'
              - 's3:PutObject'
            Resource:
              - 'arn:aws:s3:::nyc-tlc/*'
              - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
              - !Sub 'arn:aws:s3:::${ArtifactBucket}'
              - !Sub 'arn:aws:s3:::sagemaker-${AWS::Region}-${AWS::AccountId}/*'
              - !Sub 'arn:aws:s3:::sagemaker-${AWS::Region}-${AWS::AccountId}'
          - Sid: AllowLogs
            Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: '*'
      Roles:
        - !Ref SageMakerRole
        - !Ref PipelineRole
        - !Ref MLOpsRole
  CloudWatchEventRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ModelName}-cwe-role-${Stage}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: mlops-cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'codepipeline:StartPipelineExecution'
                Resource: !Sub >-
                  arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${DeployPipeline}
  SageMakerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ModelName}-sagemaker-role-${Stage}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/CloudWatchSyntheticsFullAccess'
      Policies:
        - PolicyName: mlops-sagemaker-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowCloudFormation
                Effect: Allow
                Action:
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DescribeStackEvents'
                Resource:
                  - !Sub >-
                    arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ModelName}-${Stage}*
              - Sid: SageMakerTesting
                Effect: Allow
                Action:
                  - 'sagemaker:CreateExperiment'
                  - 'sagemaker:CreateTrial'
                  - 'sagemaker:DescribeEndpoint'
                  - 'sagemaker:DescribeEndpointConfig'
                  - 'sagemaker:DescribeMonitoringSchedule'
                  - 'sagemaker:DescribeProcessingJob'
                  - 'sagemaker:InvokeEndpoint'
                  - 'sagemaker:ListMonitoringExecutions'
                  - 'sagemaker:Search'
                Resource: '*'
              - Sid: AllowCodePipeline
                Effect: Allow
                Action:
                  - 'codepipeline:GetPipeline'
                  - 'codepipeline:GetPipelineState'
                  - 'codepipeline:GetPipelineExecution'
                  - 'codepipeline:PutApprovalResult'
                  - 'codepipeline:PutJobFailureResult'
                  - 'codepipeline:PutJobSuccessResult'
                Resource: '*'
              - Sid: AllowCloudWatch
                Effect: Allow
                Action:
                  - 'cloudwatch:PutDashboard'
                  - 'cloudwatch:PutMetricData'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'cloudwatch:DeleteAlarms'
                  - 'cloudwatch:PutDashboard'
                  - 'cloudwatch:DeleteDashboards'
                  - 'iam:GetRole'
                Resource: '*'
              - Sid: AllowPassRoleLambda
                Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
                Condition:
                  StringEquals:
                    'iam:PassedToService': lambda.amazonaws.com
              - Sid: ListImagesInRepository
                Effect: Allow
                Action:
                  - 'ecr:ListImages'
                Resource: 
                  - !Sub >-
                    arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ModelName}
              - Sid: GetAuthorizationToken
                Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: '*'
              - Sid: ManageRepositoryContents
                Effect: Allow
                Action:
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:GetRepositoryPolicy'
                  - 'ecr:TagResource'
                  - 'ecr:UntagResource'
                  - 'ecr:DescribeRepositories'
                  - 'ecr:ListImages'
                  - 'ecr:ListTagsForResource'
                  - 'ecr:DescribeImages'
                  - 'ecr:BatchGetImage'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:CreateRepository'
                  - 'ecr:PutImage'
                Resource: 
                  - !Sub >-
                    arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ModelName}*
  PipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ModelName}-pipeline-role-${Stage}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: mlops-pipeline
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudFormation
                Effect: Allow
                Action:
                  - 'cloudformation:*'
                  - 'lambda:AddPermission'
                  - 'lambda:CreateFunction'
                  - 'lambda:DeleteFunction'
                  - 'lambda:InvokeFunction'
                Resource: '*'
              - Sid: CodeBuild
                Effect: Allow
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: '*'
              - Sid: AllowPassRoleCloudFormation
                Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: !GetAtt MLOpsRole.Arn
  MLOpsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ModelName}-deploy-role-${Stage}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: mlops-deploy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudFormation
                Effect: Allow
                Action:
                  - 'cloudformation:*'
                  - 'iam:AttachRolePolicy'
                  - 'iam:CreateRole'
                  - 'iam:CreatePolicy'
                  - 'iam:GetRole'
                  - 'iam:GetRolePolicy'
                  - 'iam:DeleteRole'
                  - 'iam:DetachRolePolicy'
                  - 'iam:PutRolePolicy'
                  - 'iam:PassRole'
                  - 'iam:DeleteRolePolicy'
                  - 'iam:CreateServiceLinkedRole'
                  - 'lambda:InvokeFunction'
                Resource: '*'
              - Sid: SageMakerDeployment
                Effect: Allow
                Action:
                  - 'sagemaker:CreateEndpoint'
                  - 'sagemaker:CreateEndpointConfig'
                  - 'sagemaker:CreateModel'
                  - 'sagemaker:DeleteEndpoint'
                  - 'sagemaker:DeleteEndpointConfig'
                  - 'sagemaker:DeleteModel'
                  - 'sagemaker:DescribeEndpoint'
                  - 'sagemaker:DescribeEndpointConfig'
                  - 'sagemaker:DescribeModel'
                  - 'sagemaker:UpdateEndpointWeightsAndCapacities'
                  - 'kms:CreateGrant'
                Resource: '*'
              - Sid: ApiDeployment
                Effect: Allow
                Action:
                  - 'apigateway:*'
                  - 'application-autoscaling:DeregisterScalableTarget'
                  - 'application-autoscaling:DeleteScalingPolicy'
                  - 'application-autoscaling:DescribeScalingPolicies'
                  - 'application-autoscaling:PutScalingPolicy'
                  - 'application-autoscaling:DescribeScalingPolicies'
                  - 'application-autoscaling:RegisterScalableTarget'
                  - 'application-autoscaling:DescribeScalableTargets'
                  - 'cloudwatch:DeleteAlarms'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'codedeploy:*'
                  - 'lambda:AddPermission'
                  - 'lambda:CreateAlias'
                  - 'lambda:CreateFunction'
                  - 'lambda:DeleteAlias'
                  - 'lambda:DeleteFunction'
                  - 'lambda:GetFunction'
                  - 'lambda:GetAlias'
                  - 'lambda:ListTags'
                  - 'lambda:ListVersionsByFunction'
                  - 'lambda:PublishVersion'
                  - 'lambda:RemovePermission'
                  - 'lambda:UpdateFunctionCode'
                  - 'lambda:UpdateFunctionConfiguration'
                  - 'sns:CreateTopic'
                  - 'sns:DeleteTopic'
                  - 'sns:GetTopicAttributes'
                  - 'sns:ListTopics'
                Resource: '*'
              - Sid: AllowPassRoleSageMaker
                Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
                Condition:
                  StringEquals:
                    'iam:PassedToService': sagemaker.amazonaws.com
