Description: Deploy a model at Sagemaker
Parameters:
  ImageRepoUri:
    Type: String
    Description: Uri of the docker (ECR) model image
  ModelName:
    Type: String
    Description: Name of the model
  MLOpsRoleArn:
    Type: String
    Description: The role for executing the deployment

Resources:
  Model:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: !Sub ${ModelName}
      PrimaryContainer:
        Image: !Ref ImageRepoUri
        ModelDataUrl: !Sub s3://${ModelName}/models
        Mode: MultiModel
      ExecutionRoleArn: !Ref MLOpsRoleArn

  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: ml.t2.medium
          ModelName: !GetAtt Model.ModelName
          VariantName: AllTraffic
      EndpointConfigName: !Sub ${ModelName}
      Tags:
        - Key: Name
          Value: !Sub ${ModelName}

  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub ${ModelName}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
      Tags:
        - Key: Name
          Value: !Sub ${ModelName}
