Description: Wait for a training job
Parameters:
  ModelName:
    Type: String
    Description: Name of the model
  TrainJobId:
    Type: String
    Description: Id of the Codepipeline + SagemakerJobs
  TrainJobRequest:
    Type: String
    Description: Training job request json

Resources:
  SagemakerTrainingJob:
    Type: Custom::TrainingJob
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:sagemaker-cfn-training-job"
      TrainingJobName: !Sub mlops-${ModelName}-${TrainJobId}
      TrainingJobRequest: !Ref TrainJobRequest
      ExperimentName: !Ref ModelName
      TrialName: !Ref TrainJobId
